services:
  zoe:
    build:
      context: ..
      dockerfile: deployments/Dockerfile
    platform: linux/amd64
    user: ${UID:-1000}:${GID:-1000}
    ports:
      - '2222:2222'
      - '127.0.0.1:8080:8080'
      - '127.0.0.1:9999:9999'
    volumes:
      - ./.volume:/tmp/zoe
