version: '3.9'

services:
  zoe:
    build:
      context: ..
      dockerfile: deployments/Dockerfile
    platform: linux/amd64
    ports:
      - '2222:2222'
      - '127.0.0.1:8080:8080'
    volumes:
      - ./.volume:/svc/zoe
