loggers:
  - console://
  - sqlite3://zoe.db

monitor:
  bind: 127.0.0.1:8080
  database: sqlite3://zoe.db

services:
  # simulate the SSH service
  ssh:
    bind: :2222
    banner: SSH-2.0-OpenSSH_9.5

    # the valid username and password and set null to disable the authentication
    # default: null

    ciphers:
      - ssh-ed25519
