name: Update the Daily Update

on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * *'

jobs:
  update_daily_update:
    name: Update the Daily Update
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Get the latest Daily Update
        run: |
          curl -sL "${{ secrets.ZOE_SERVER }}/messages/daily-popular" > docs/daily-popular.md
          git add daily-popular.md
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "[skip ci][AUTO] Update the Daily Update"
          commit_options: '--no-verify --signoff'
