name: Test and Build Go package

on:
  pull_request:

jobs:
  testing:
    name: Test the go package
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        go-version:
          - '1.22'
          - '1.21'

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Show Go version
        run: go version

      - name: Install SASS
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew install sass/sass/sass
          brew link --force sass/sass/sass || true

      - name: Build the go package
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          make build
      - name: Test the go package
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          make test

  buildImage:
    name: Build the docker image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v2
      - name: Build the docker image
        uses: docker/build-push-action@v4
        with:
          push: false
          platforms: linux/amd64
          context: .
          file: ./deployments/Dockerfile
